export const EXTEND_TAIL = "EXTEND_TAIL",
    MOVE_PLAYER = 'MOVE_PLAYER',
    RANDOMIZE_FOOD = 'RANDOMIZE_FOOD',
    RANDOMIZE_PLAYER = 'RANDOMIZE_PLAYER',
    SET_VELOCITY = 'SET_VELOCITY',
    SET_PLAYGROUND_SIZE = 'SET_PLAYGROUND_SIZE',
    SET_SCORE = 'SET_SCORE',
    SET_SPEED = 'SET_SPEED';